theme: jekyll-theme-merlot
title: License Education for Game Developers
description:I am <https://www.linkedin.com/in/pol-bosch-27b507140/>(Pol Bosch), student of the <https://www.citm.upc.edu/ing/estudis/graus-videojocs/>(Bachelor’s Degree in Video Games by UPC at CITM). This content is generated for the second year’s subject Project 2, under supervision of lecturer <https://es.linkedin.com/in/ricardpillosu>(Ricard Pillosu).
